import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/lib/providers/ThemeProvider';
import Header from '@/components/layout/Header';
import ReduxProvider from '@/lib/providers/ReduxProvider';
import Spinner from '@/components/Spinner';

const robotoHeading = Roboto({
  subsets: ['latin'],
  variable: '--font-heading',
});

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'dark',
        'antialiased',
        'font-sans',
        inter.variable,
        robotoHeading.variable
      )}
      suppressHydrationWarning
    >
      <body className="mx-auto min-h-full flex flex-col">
        <ReduxProvider>
          <ThemeProvider>
            <Header />
            {children}
            <Spinner />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
